import type { SignalSource } from './signal'

/**
 * Analysts are the people signals get assigned to (the `assignedTo` / `owner` references).
 * 25 are generated by the fixtures.
 */
export type AnalystRole = 'analyst' | 'lead' | 'admin'

export type Analyst = {
  id: string
  name: string
  email: string
  role: AnalystRole
  region: string
}

/**
 * A concrete signal source instance. There are 12 of them, each belonging to one of the
 * six `SignalSource` categories.
 */
export type Source = {
  id: string
  name: string
  category: SignalSource
  /** Source trust score in [0, 100]. */
  trustScore: number
}

export const ANALYST_ROLES = ['analyst', 'lead', 'admin'] as const
