/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DxMetricsRouteImport } from './routes/dx-metrics'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals/index'
import { Route as SignalsIdRouteImport } from './routes/signals/$id'
import { Route as ApiSimulateErrorRouteImport } from './routes/api/simulate-error'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDxMetricsRouteImport } from './routes/api/dx-metrics'
import { Route as ApiSignalsIdRouteImport } from './routes/api/signals.$id'
import { Route as ApiDashboardSummaryRouteImport } from './routes/api/dashboard.summary'
import { Route as ApiCompareIdRouteImport } from './routes/api/compare.$id'
import { Route as ApiSignalsIdEventsRouteImport } from './routes/api/signals.$id.events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DxMetricsRoute = DxMetricsRouteImport.update({
  id: '/dx-metrics',
  path: '/dx-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIdRoute = SignalsIdRouteImport.update({
  id: '/signals/$id',
  path: '/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulateErrorRoute = ApiSimulateErrorRouteImport.update({
  id: '/api/simulate-error',
  path: '/api/simulate-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDxMetricsRoute = ApiDxMetricsRouteImport.update({
  id: '/api/dx-metrics',
  path: '/api/dx-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsIdRoute = ApiSignalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSignalsRoute,
} as any)
const ApiDashboardSummaryRoute = ApiDashboardSummaryRouteImport.update({
  id: '/api/dashboard/summary',
  path: '/api/dashboard/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareIdRoute = ApiCompareIdRouteImport.update({
  id: '/api/compare/$id',
  path: '/api/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsIdEventsRoute = ApiSignalsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiSignalsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dx-metrics': typeof DxMetricsRoute
  '/incidents': typeof IncidentsRoute
  '/settings': typeof SettingsRoute
  '/api/dx-metrics': typeof ApiDxMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/signals': typeof ApiSignalsRouteWithChildren
  '/api/simulate-error': typeof ApiSimulateErrorRoute
  '/signals/$id': typeof SignalsIdRoute
  '/signals/': typeof SignalsIndexRoute
  '/api/compare/$id': typeof ApiCompareIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/signals/$id': typeof ApiSignalsIdRouteWithChildren
  '/api/signals/$id/events': typeof ApiSignalsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dx-metrics': typeof DxMetricsRoute
  '/incidents': typeof IncidentsRoute
  '/settings': typeof SettingsRoute
  '/api/dx-metrics': typeof ApiDxMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/signals': typeof ApiSignalsRouteWithChildren
  '/api/simulate-error': typeof ApiSimulateErrorRoute
  '/signals/$id': typeof SignalsIdRoute
  '/signals': typeof SignalsIndexRoute
  '/api/compare/$id': typeof ApiCompareIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/signals/$id': typeof ApiSignalsIdRouteWithChildren
  '/api/signals/$id/events': typeof ApiSignalsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dx-metrics': typeof DxMetricsRoute
  '/incidents': typeof IncidentsRoute
  '/settings': typeof SettingsRoute
  '/api/dx-metrics': typeof ApiDxMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/signals': typeof ApiSignalsRouteWithChildren
  '/api/simulate-error': typeof ApiSimulateErrorRoute
  '/signals/$id': typeof SignalsIdRoute
  '/signals/': typeof SignalsIndexRoute
  '/api/compare/$id': typeof ApiCompareIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/signals/$id': typeof ApiSignalsIdRouteWithChildren
  '/api/signals/$id/events': typeof ApiSignalsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dx-metrics'
    | '/incidents'
    | '/settings'
    | '/api/dx-metrics'
    | '/api/health'
    | '/api/incidents'
    | '/api/signals'
    | '/api/simulate-error'
    | '/signals/$id'
    | '/signals/'
    | '/api/compare/$id'
    | '/api/dashboard/summary'
    | '/api/signals/$id'
    | '/api/signals/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dx-metrics'
    | '/incidents'
    | '/settings'
    | '/api/dx-metrics'
    | '/api/health'
    | '/api/incidents'
    | '/api/signals'
    | '/api/simulate-error'
    | '/signals/$id'
    | '/signals'
    | '/api/compare/$id'
    | '/api/dashboard/summary'
    | '/api/signals/$id'
    | '/api/signals/$id/events'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dx-metrics'
    | '/incidents'
    | '/settings'
    | '/api/dx-metrics'
    | '/api/health'
    | '/api/incidents'
    | '/api/signals'
    | '/api/simulate-error'
    | '/signals/$id'
    | '/signals/'
    | '/api/compare/$id'
    | '/api/dashboard/summary'
    | '/api/signals/$id'
    | '/api/signals/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DxMetricsRoute: typeof DxMetricsRoute
  IncidentsRoute: typeof IncidentsRoute
  SettingsRoute: typeof SettingsRoute
  ApiDxMetricsRoute: typeof ApiDxMetricsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
  ApiSignalsRoute: typeof ApiSignalsRouteWithChildren
  ApiSimulateErrorRoute: typeof ApiSimulateErrorRoute
  SignalsIdRoute: typeof SignalsIdRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
  ApiCompareIdRoute: typeof ApiCompareIdRoute
  ApiDashboardSummaryRoute: typeof ApiDashboardSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dx-metrics': {
      id: '/dx-metrics'
      path: '/dx-metrics'
      fullPath: '/dx-metrics'
      preLoaderRoute: typeof DxMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$id': {
      id: '/signals/$id'
      path: '/signals/$id'
      fullPath: '/signals/$id'
      preLoaderRoute: typeof SignalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulate-error': {
      id: '/api/simulate-error'
      path: '/api/simulate-error'
      fullPath: '/api/simulate-error'
      preLoaderRoute: typeof ApiSimulateErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dx-metrics': {
      id: '/api/dx-metrics'
      path: '/api/dx-metrics'
      fullPath: '/api/dx-metrics'
      preLoaderRoute: typeof ApiDxMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals/$id': {
      id: '/api/signals/$id'
      path: '/$id'
      fullPath: '/api/signals/$id'
      preLoaderRoute: typeof ApiSignalsIdRouteImport
      parentRoute: typeof ApiSignalsRoute
    }
    '/api/dashboard/summary': {
      id: '/api/dashboard/summary'
      path: '/api/dashboard/summary'
      fullPath: '/api/dashboard/summary'
      preLoaderRoute: typeof ApiDashboardSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare/$id': {
      id: '/api/compare/$id'
      path: '/api/compare/$id'
      fullPath: '/api/compare/$id'
      preLoaderRoute: typeof ApiCompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals/$id/events': {
      id: '/api/signals/$id/events'
      path: '/events'
      fullPath: '/api/signals/$id/events'
      preLoaderRoute: typeof ApiSignalsIdEventsRouteImport
      parentRoute: typeof ApiSignalsIdRoute
    }
  }
}

interface ApiSignalsIdRouteChildren {
  ApiSignalsIdEventsRoute: typeof ApiSignalsIdEventsRoute
}

const ApiSignalsIdRouteChildren: ApiSignalsIdRouteChildren = {
  ApiSignalsIdEventsRoute: ApiSignalsIdEventsRoute,
}

const ApiSignalsIdRouteWithChildren = ApiSignalsIdRoute._addFileChildren(
  ApiSignalsIdRouteChildren,
)

interface ApiSignalsRouteChildren {
  ApiSignalsIdRoute: typeof ApiSignalsIdRouteWithChildren
}

const ApiSignalsRouteChildren: ApiSignalsRouteChildren = {
  ApiSignalsIdRoute: ApiSignalsIdRouteWithChildren,
}

const ApiSignalsRouteWithChildren = ApiSignalsRoute._addFileChildren(
  ApiSignalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DxMetricsRoute: DxMetricsRoute,
  IncidentsRoute: IncidentsRoute,
  SettingsRoute: SettingsRoute,
  ApiDxMetricsRoute: ApiDxMetricsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
  ApiSignalsRoute: ApiSignalsRouteWithChildren,
  ApiSimulateErrorRoute: ApiSimulateErrorRoute,
  SignalsIdRoute: SignalsIdRoute,
  SignalsIndexRoute: SignalsIndexRoute,
  ApiCompareIdRoute: ApiCompareIdRoute,
  ApiDashboardSummaryRoute: ApiDashboardSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
